spring.application.name=Atividade1_clima
api.url.bh = https://api.open-meteo.com/v1/forecast?latitude=-19.9167&longitude=-43.9345&current=temperature_2m
api.url.cidade = https://geocoding-api.open-meteo.com/v1/search?name=